apiVersion: v1
kind: Service
metadata:
  name: airdex-api-service
  labels:
    run: airdex-api-service
spec:
  selector:
    app: airdex-api
    tier: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: LoadBalancer