apiVersion: v1
kind: Deployment
metadata:
  name: airdex-depployment

spec:
  selector:
    matchLabels:
      app: airdex
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: airdex
        tier: backend
      spec:
        containers:
          - name: airdex-container
            image: 530820415924.dkr.ecr.us-east-1.amazonaws.com/airdex-repo:latest

